{
 "title": "Nextcloud",
 "description": "nextcloud-exporter metrics",
 "tags": [
  "cloud",
  "storage",
  "prometheus"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nextcloud Uptime",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "avg(nextcloud_up)" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nextcloud_free_space_bytes", "legendFormat": "Available Storage" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nextcloud_apps_updates_available_total",
     "legendFormat": "Apps with Updates"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nextcloud_scrape_errors_total", "legendFormat": "Scrape Errors" }
   ]
  },
  { "title": "content", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "type": "stat",
   "gridPos": { "h": 12, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nextcloud_users_total", "legendFormat": "Users Total" },
    { "expr": "nextcloud_active_users_total", "legendFormat": "Users Active (5m)" }
   ]
  },
  {
   "title": "Shares",
   "type": "stat",
   "gridPos": { "h": 12, "w": 4, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nextcloud_shares_total", "legendFormat": "{{type}}" },
    {
     "expr": "nextcloud_shares_federated_total",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 7, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(nextcloud_files_total)", "legendFormat": "Stored Files" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 7, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nextcloud_apps_installed_total", "legendFormat": "Installed Apps" }
   ]
  },
  { "title": "backend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nextcloud_php_upload_max_size_bytes",
     "legendFormat": "PHP Upload Limit"
    },
    {
     "expr": "nextcloud_php_memory_limit_bytes",
     "legendFormat": "PHP Memory Limit"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nextcloud_database_size_bytes", "legendFormat": "DB size" }
   ]
  },
  {
   "title": "Versions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nextcloud_system_info", "legendFormat": "NC {{version}}" },
    { "expr": "nextcloud_php_info", "legendFormat": "PHP {{version}}" }
   ]
  }
 ]
}