{
 "title": "Nextcloud Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nextcloud Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nextcloud_up" }
   ]
  },
  {
   "title": "Total Users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nextcloud_users_total" }
   ]
  },
  {
   "title": "Daily Total Active Users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nextcloud_active_users_total" }
   ]
  },
  {
   "title": "Total Files",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "nextcloud_files_total" }
   ]
  },
  {
   "title": "Number of Apps Installed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nextcloud_apps_installed_total" }
   ]
  },
  {
   "title": "Pending App Updates",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nextcloud_apps_updates_available_total"
    }
   ]
  },
  {
   "title": "Free Space (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "nextcloud_free_space_bytes" }
   ]
  },
  {
   "title": "Database Size (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "nextcloud_database_size_bytes" }
   ]
  },
  {
   "title": "Total Hourly Users",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nextcloud_active_users_hourly_total"
    }
   ]
  },
  {
   "title": "Nextcloud Shares by Type",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 5, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nextcloud_shares_total" }
   ]
  },
  {
   "title": "Nextcloud Version",
   "type": "table",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 16 },
   "targets": [
    { "expr": "nextcloud_system_info" }
   ]
  },
  {
   "title": "Database Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 16, "y": 16 },
   "targets": [
    { "expr": "nextcloud_database_info" }
   ]
  },
  {
   "title": "Scraper Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nextcloud_scrape_errors_total" }
   ]
  },
  {
   "title": "Total Shares via Federation",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 5, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nextcloud_shares_federated_total"
    }
   ]
  },
  { "title": "PHP Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "PHP Memory Limit (Bytes)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nextcloud_php_memory_limit_bytes"
    }
   ]
  },
  {
   "title": "PHP Upload Max Size (Bytes)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 5, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nextcloud_php_upload_max_size_bytes"
    }
   ]
  },
  {
   "title": "PHP Version",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 11, "y": 32 },
   "targets": [
    { "expr": "nextcloud_php_info" }
   ]
  }
 ]
}