module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.25.0

toolchain go1.25.2

replace cloud.google.com/go => cloud.google.com/go v0.123.0

exclude github.com/linode/linodego v1.0.0

exclude github.com/grpc-ecosystem/grpc-gateway v1.14.7

exclude google.golang.org/api v0.30.0

require github.com/prometheus/prometheus v0.310.0 // cmd/promtool
